### ISSUE TITLE
Not able to add alignment file under template Structured-birth-death-model in 

### ISSUE THREAD

**Issue by alka26** [Taming-the-BEAST/Structured-birth-death-model#1]
Dear moderator
I wish to analyze 45 viral sequences in structured birth death model in Beast 2. I have alignment file in fasta format generated from Bioedit. After installing/upgrading bdmm, restarted Beauti, then under Template sub menu selected multitypebirthdeath. After clicking 'add alignment' , selected the file alignment file in fasta format. This was followed by pop up window "choose the datatype of alignment Align...". After selecting nucleotide and pressed 'ok'. Then nothing happens

Hope to hear from you

Regards

Alka

**Comment by laduplessis** [comment]
Hi Alka, 

Please try to add one of the example alignment files in Beauti first, e.g. the one included with this tutorial or one of the examples included with Beast2 itself. If that works, then it is probably a problem with your alignment file. Check it is really in the intended format and that you can open it with other programs such as AliView. 

Best regards,
Louis

**Comment by alka26** [comment]
Yes I did that and  I was doing this exercise  following tutorial (Tutorial using BEAST v2.4.7
Structured birth-death model). The example file h3n2_2deme.fna was also not taken by BEAUTi.

Regards

**Comment by laduplessis** [comment]
Hi Alka, 

Can you load *any* alignments into Beauti? (with or without the multitypebirthdeath template)

Best regards,
Louis

**Comment by alka26** [comment]
In standard template, when option of import alignment then, it is taking the alignment sequences file.

Regards

**Comment by laduplessis** [comment]
I can't reproduce the problem. Using Beast 2.4.7 it works for me without any problems.

You could try to update Beast2 to Beast 2.5. Or you could try to load the alignment using the + button in the lower left corner or simply by dragging it into the Beauti window. If none of those work I would suggest contacting the Beast2 or MultitypeBirthDeath developers.

**Comment by alka26** [comment]
I am using BEAST v2.5 and Java v 8 and used  + button. Not understanding whats the problem...is it possible for you to generate XML file so that I can move forward with analysis.

Thanks and regards

**Comment by laduplessis** [comment]
Hi Alka, 

I don't know what the problem is, I cannot replicate it. This is the repository for a tutorial on the structured birth-death model. Your issue appears to be with either Beast2, the MultitypeBirthdeath package or due to a problem with your alignment files. I can't help you with these issues, but perhaps the developers of Beast2 or the MultitypeBirthDeath package can.

Try to isolate the cause of the problem. Is it:
- The alignment files
- The version of Beast2
- The MultitypeBirthdeath package
- Something with your computer

The xml-file for the tutorial is available on the tutorial website: https://taming-the-beast.org/tutorials/Structured-birth-death-model/

Good luck!
Louis

**Comment by alka26** [comment]
thanks
